### ISSUE TITLE
Please officially add diamond versions of tools, the current ones break way too fast

### ISSUE THREAD

**Issue by AmyMoriyama** [t-affeldt/sickles#5]
On my not-so-large farm on my server, I break a scythe every couple of passes. It becomes quite expensive quite quickly, but that is not even the biggest issue with this, the biggest issue is having to go to the farm with half an inventory of scythes just for one harvest.

Thank you, this mod is great.

**Comment by FloraMaeWolfe** [comment]
It seems the dev may have abandoned this mod. Since I use this mod on my server, I am attempting to update it and improve it. That can be found here if interested:
https://gitlab.com/validandloved/sickles

I don't have diamond versions as of this reply but there is a mithril scythe added already with plans of diamond and mithril for sickles and scythes.

**Comment by t-affeldt** [comment]
Hello. It's been a long time but I've finally found some time.
I haven't added any new tools yet but I have dratically increased durability of the existing ones. So you should be able to use them without going bancrupt. :D
